# Generated by Django 5.1.3 on 2024-11-27 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomobilioModelis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marke", models.CharField(max_length=100, verbose_name="Markė")),
                ("modelis", models.CharField(max_length=100, verbose_name="Modelis")),
            ],
        ),
        migrations.CreateModel(
            name="Paslauga",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pavadinimas",
                    models.CharField(max_length=255, verbose_name="Pavadinimas"),
                ),
                (
                    "kaina",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Kaina"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Automobilis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valstybinis_nr",
                    models.CharField(max_length=8, verbose_name="Valstybinis numeris"),
                ),
                (
                    "vin_kodas",
                    models.CharField(max_length=17, verbose_name="VIN kodas"),
                ),
                ("klientas", models.CharField(max_length=255, verbose_name="Klientas")),
                (
                    "automobilio_modelis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.automobiliomodelis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uzsakymas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.DateField(auto_now_add=True, verbose_name="Data")),
                (
                    "automobilis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.automobilis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UzsakymoEilute",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("kiekis", models.PositiveIntegerField(verbose_name="Kiekis")),
                (
                    "paslauga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.paslauga",
                    ),
                ),
                (
                    "uzsakymas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.uzsakymas",
                    ),
                ),
            ],
        ),
    ]
