# Generated by Django 5.1.3 on 2024-11-28 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autoservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automobiliomodelis",
            options={
                "verbose_name": "Automobilio modelis",
                "verbose_name_plural": "Automobiliu modeliai",
            },
        ),
        migrations.AlterModelOptions(
            name="automobilis",
            options={
                "verbose_name": "Automobilis",
                "verbose_name_plural": "Automobiliai",
            },
        ),
        migrations.AlterModelOptions(
            name="paslauga",
            options={"verbose_name": "Paslauga", "verbose_name_plural": "Paslaugos"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymas",
            options={"verbose_name": "Užsakymas", "verbose_name_plural": "Užsakymai"},
        ),
        migrations.AlterModelOptions(
            name="uzsakymoeilute",
            options={
                "verbose_name": "Užsakymo eilutė",
                "verbose_name_plural": "Užsakymo eilutės",
            },
        ),
    ]
