# Generated by Django 5.1.3 on 2024-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoservice", "0002_alter_automobiliomodelis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzsakymas",
            name="statusas",
            field=models.CharField(
                choices=[
                    ("nepradetas", "Nepradetas"),
                    ("vykdomas", "Vykdomas"),
                    ("uzbaigtas", "Uzbaigtas"),
                    ("atsauktas", "Atsauktas"),
                ],
                default="nepradetas",
                max_length=20,
            ),
        ),
    ]
