# Generated by Django 5.1.3 on 2024-12-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autoservice", "0004_automobilis_nuotrauka_alter_uzsakymas_statusas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uzsakymas",
            name="grazinimo_terminas",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gražinimo terminas"
            ),
        ),
        migrations.AddField(
            model_name="uzsakymas",
            name="vartotojas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
