# Generated by Django 5.1.3 on 2024-12-06 10:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autoservice", "0005_uzsakymas_grazinimo_terminas_uzsakymas_vartotojas"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilis",
            name="aprasymas",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Aprašymas"
            ),
        ),
    ]
