# Generated by Django 5.1.3 on 2024-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autoservice", "0008_profilis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilis",
            options={"verbose_name": "Profilis", "verbose_name_plural": "Profiliai"},
        ),
    ]
